server:
  port: 8080

  kafka:
    bootstrap-servers: localhost:9082
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer